// This class handles the devices connecting to the internal MQTT broker. This includes both device provisioning
// and minimal wrappers for actual data exchange. The device class is responsible for generating/parsing the payload.

import { TypedEmitter } from 'tiny-typed-emitter'
import log from '@/util/logging'
import type { Broker, Client, PublishPacket } from '../mqtt-broker'
import type { Metadata } from '../thinq'
import type { ClipDeployMessage, ClipMessage } from './clip'
import { generateDeployResponse } from './provisioning'

type DeviceEvents = {
    data: (packet: Buffer) => void
    // Kept in the common downstream-device event surface. ThinQ2 responses are carried through
    // bridge messages rather than this event, while ThinQ1 command responses use it directly.
    response: (body: Record<string, unknown>) => void
    sendData: (buf: Buffer) => void
    close: () => void
}

function traceMqtt(direction: string, packet: PublishPacket) {
    log(
        'mqtt-trace',
        JSON.stringify({
            direction,
            topic: packet.topic,
            qos: packet.qos,
            dup: packet.dup,
            retain: packet.retain,
            messageId: packet.messageId,
            payload: packet.payload.toString('utf-8'),
        }),
    )
}

export class Device extends TypedEmitter<DeviceEvents> {
    // this could be a stream but why bother...
    readonly platform = 'thinq2'

    constructor(
        readonly broker: Broker,
        readonly topic: string,
        readonly id: string,
        readonly meta: Metadata,
        readonly sourceIp?: string,
    ) {
        super()
    }

    /**
     * What the appliance said about itself when it announced. The bridge sends this on to
     * the LG cloud instead of describing the appliance from a template, so the cloud is
     * told the model, firmware, modem and timezone the appliance actually reports.
     */
    deployProfile: ClipDeployMessage | undefined

    private bridgeMessageListeners = new Set<(payload: ClipMessage) => void>()

    onBridgeMessage(listener: (payload: ClipMessage) => void) {
        this.bridgeMessageListeners.add(listener)
    }

    removeBridgeMessageListener(listener: (payload: ClipMessage) => void) {
        this.bridgeMessageListeners.delete(listener)
    }

    emitBridgeMessage(payload: ClipMessage) {
        for (const listener of this.bridgeMessageListeners) listener(payload)
    }

    send(cmd: string, type: number, data: string | object) {
        const messagestr = JSON.stringify({ did: this.id, mid: Date.now(), cmd: cmd, type: type, data: data })
        const packet = { topic: this.topic, retain: false, qos: 0 as const, dup: false, payload: messagestr }
        traceMqtt('rethink->device', packet)
        this.broker.publish(packet, null /* message generated by the broker itself */)
    }

    send_packet(buf: Buffer) {
        this.emit('sendData', buf)
        this.send('packet', 1, buf.toString('hex'))
    }

    forward_message(payload: ClipMessage) {
        if (typeof payload.data === 'string' && (payload.cmd === 'packet' || payload.cmd === 'ack')) {
            this.emit('sendData', Buffer.from(payload.data, 'hex'))
        }

        const packet = {
            topic: this.topic,
            retain: false,
            qos: 0 as const,
            dup: false,
            payload: JSON.stringify(payload),
        }
        traceMqtt('rethink->device', packet)
        this.broker.publish(packet, null)
    }
}

function trimNull(buf: Buffer) {
    if (!buf?.length || buf[buf.length - 1]) return buf
    return buf.subarray(0, buf.length - 1)
}

type ClientWithExtra = Client & {
    deviceObj: undefined | Device
    deployMsg: undefined | ClipDeployMessage
}

type DeviceAcceptorEvents = {
    newDevice: (dev: Device) => void
    dropDevice: (id: string) => void
}

export class DeviceAcceptor extends TypedEmitter<DeviceAcceptorEvents> {
    clientsById: Record<string, Client> = {}
    constructor(readonly broker: Broker) {
        super()

        broker.on('publish', (packet, client) => {
            log('incoming', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)

            if (!client) return

            try {
                if (packet.topic.indexOf('clip/') >= 0) {
                    traceMqtt('device->rethink', packet)
                    const payload = JSON.parse(trimNull(Buffer.from(packet.payload)).toString('utf-8'))
                    this.mqtt(packet.topic, payload, client as ClientWithExtra)
                }
            } catch (err) {
                console.warn(err, packet.payload.toString('hex'))
            }
        })

        broker.on('disconnect', this.disconnected.bind(this))
    }

    mqtt(topic: string, payload: ClipMessage, client: ClientWithExtra) {
        // experiment: try to support devices which use other topic formats
        topic = topic.replace(/^.*\/clip/, 'clip')

        if (topic === `clip/message/devices/${payload.did}`) {
            if (payload.cmd === 'completeProvisioning_ack') {
                this.completeProvisioning(payload.did, payload, client)
                return
            }

            if (payload.cmd === 'req_timesync' && client.deviceObj && payload.did === client.deviceObj.id) {
                this.timeSyncRequest(client)
                return
            }

            if (client.deviceObj && payload.did === client.deviceObj.id) {
                if (payload.cmd === 'device_packet' && typeof payload.data === 'string') {
                    const buf = Buffer.from(payload.data, 'hex')
                    client.deviceObj.emit('data', buf)
                }

                // Preserve the complete device JSON for the cloud bridge. Commands such as
                // modem_cmd cannot be represented by the legacy raw-buffer data event.
                client.deviceObj.emitBridgeMessage(payload)
            }
        }

        if (topic === `clip/provisioning/devices/${payload.did}`) {
            if (payload.cmd === 'undeploy') {
                // The appliance is dropping its provisioning with us. Everything tied to it
                // has to go: completeProvisioning refuses a second registration while the
                // device object is still around, so leaving it would make the appliance's
                // next deploy a no-op and it would never come back. It also stops sending
                // state records in the meantime, so keeping the device would leave Home
                // Assistant showing an appliance that has quietly gone silent.
                log('status', payload.did, 'undeployed itself; dropping its registration')
                this.disconnected(client)
                client.deployMsg = undefined
                return
            }

            if (payload.cmd === 'preDeploy' || payload.cmd === 'deploy') {
                client.deployMsg = payload as ClipDeployMessage
                // The appliance re-announces itself periodically; keep the latest, so a
                // bridge that connects later describes the appliance as it is now.
                if (client.deviceObj) client.deviceObj.deployProfile = payload as ClipDeployMessage
                const packet = {
                    topic: `lime/devices/${payload.did}`,
                    retain: false,
                    qos: 0 as const,
                    dup: false,
                    payload: JSON.stringify(generateDeployResponse(payload as ClipDeployMessage)),
                }
                traceMqtt('rethink->device', packet)
                this.broker.publish(packet, null)
            }
        }
    }

    completeProvisioning(deviceId: string, _payload: ClipMessage, client: ClientWithExtra) {
        if (!client.deployMsg) {
            log('status', `${deviceId} acknowledged provisioning it never started; it will not be registered`)
            return
        }

        if (client.deviceObj) {
            log('status', `${deviceId} acknowledged provisioning twice; keeping the registration it already has`)
            return
        }

        if (this.clientsById[deviceId]) {
            log('status', `${deviceId} connected again; dropping its previous connection`)
            this.clientsById[deviceId].destroy()
        }

        this.clientsById[deviceId] = client

        const meta: Metadata = {
            modelId: client.deployMsg.kind,
            modelName: client.deployMsg.data?.appInfo?.modelName,
            swVersion: client.deployMsg.data?.appInfo?.softVer,
            deviceType: client.deployMsg.data?.appInfo?.DeviceType,
        }

        const dev = new Device(this.broker, `lime/devices/${deviceId}`, deviceId, meta, client.remoteAddress)
        dev.deployProfile = client.deployMsg
        client.deviceObj = dev
        this.emit('newDevice', dev)
    }

    timeSyncRequest(client: ClientWithExtra) {
        const now = new Date()
        const buf = Buffer.alloc(7)
        buf[0] = now.getUTCFullYear() % 100
        buf[1] = now.getUTCMonth()
        buf[2] = now.getUTCDate()
        buf[3] = now.getUTCHours()
        buf[4] = now.getUTCMinutes()
        buf[5] = now.getUTCSeconds()
        buf[6] = now.getUTCDay()

        client.deviceObj?.send('resp_timesync', 1, buf.toString('base64'))
    }

    disconnected(_client: Client) {
        const client = _client as ClientWithExtra
        if (client.deviceObj) {
            // A replacement connection may already have claimed this id before the old
            // socket's close event arrives. Do not let the old close delete the new index.
            if (this.clientsById[client.deviceObj.id] === client) delete this.clientsById[client.deviceObj.id]
            this.emit('dropDevice', client.deviceObj.id)
            client.deviceObj.emit('close')
            client.deviceObj = undefined
        }
    }
}
