// This class handles the devices connecting to the internal MQTT broker. This includes both device provisioning
// and minimal wrappers for actual data exchange. The device class is responsible for generating/parsing the payload.

import { TypedEmitter } from 'tiny-typed-emitter'
import log from '@/util/logging'
import { isSafeDeviceId } from '../device_id'
import type { Broker, Client, PublishPacket } from '../mqtt-broker'
import type { Metadata } from '../thinq'
import type { ClipDeployMessage, ClipMessage } from './clip'
import { generateDeployResponse } from './provisioning'

type DeviceEvents = {
    data: (packet: Buffer) => void
    // Kept in the common downstream-device event surface. ThinQ2 responses are carried through
    // bridge messages rather than this event, while ThinQ1 command responses use it directly.
    response: (body: Record<string, unknown>) => void
    sendData: (buf: Buffer) => void
    close: () => void
}

function traceMqtt(direction: string, packet: PublishPacket) {
    log(
        'mqtt-trace',
        JSON.stringify({
            direction,
            topic: packet.topic,
            qos: packet.qos,
            dup: packet.dup,
            retain: packet.retain,
            messageId: packet.messageId,
            payload: packet.payload.toString('utf-8'),
        }),
    )
}

export class Device extends TypedEmitter<DeviceEvents> {
    // this could be a stream but why bother...
    readonly platform = 'thinq2'

    constructor(
        readonly broker: Broker,
        readonly topic: string,
        readonly id: string,
        readonly meta: Metadata,
        readonly sourceIp?: string,
    ) {
        super()
    }

    /**
     * What the appliance said about itself when it announced. The bridge sends this on to
     * the LG cloud instead of describing the appliance from a template, so the cloud is
     * told the model, firmware, modem and timezone the appliance actually reports.
     */
    deployProfile: ClipDeployMessage | undefined

    private bridgeMessageListeners = new Set<(payload: ClipMessage) => void>()

    onBridgeMessage(listener: (payload: ClipMessage) => void) {
        this.bridgeMessageListeners.add(listener)
    }

    removeBridgeMessageListener(listener: (payload: ClipMessage) => void) {
        this.bridgeMessageListeners.delete(listener)
    }

    emitBridgeMessage(payload: ClipMessage) {
        for (const listener of this.bridgeMessageListeners) listener(payload)
    }

    send(cmd: string, type: number, data: string | object) {
        const messagestr = JSON.stringify({ did: this.id, mid: Date.now(), cmd: cmd, type: type, data: data })
        const packet = { topic: this.topic, retain: false, qos: 0 as const, dup: false, payload: messagestr }
        traceMqtt('rethink->device', packet)
        this.broker.publish(packet, null /* message generated by the broker itself */)
    }

    send_packet(buf: Buffer) {
        this.emit('sendData', buf)
        this.send('packet', 1, buf.toString('hex'))
    }

    forward_message(payload: ClipMessage) {
        if (typeof payload.data === 'string' && (payload.cmd === 'packet' || payload.cmd === 'ack')) {
            this.emit('sendData', Buffer.from(payload.data, 'hex'))
        }

        const packet = {
            topic: this.topic,
            retain: false,
            qos: 0 as const,
            dup: false,
            payload: JSON.stringify(payload),
        }
        traceMqtt('rethink->device', packet)
        this.broker.publish(packet, null)
    }
}

function trimNull(buf: Buffer) {
    if (!buf?.length || buf[buf.length - 1]) return buf
    return buf.subarray(0, buf.length - 1)
}

const MAX_PROVISIONING_TEXT_LENGTH = 128

function boundedText(value: unknown): value is string {
    return (
        typeof value === 'string' &&
        value.length > 0 &&
        value.length <= MAX_PROVISIONING_TEXT_LENGTH &&
        value.trim().length > 0
    )
}

function objectRecord(value: unknown): Record<string, unknown> | undefined {
    return value !== null && typeof value === 'object' && !Array.isArray(value)
        ? (value as Record<string, unknown>)
        : undefined
}

function topicDeviceId(topic: string, kind: 'message' | 'provisioning') {
    const prefix = `clip/${kind}/devices/`
    if (!topic.startsWith(prefix)) return undefined
    const deviceId = topic.slice(prefix.length)
    return isSafeDeviceId(deviceId) ? deviceId : undefined
}

function validMessage(payload: unknown, expectedDeviceId: string) {
    const message = objectRecord(payload)
    return message && message.did === expectedDeviceId ? (message as ClipMessage) : undefined
}

function validDeployMessage(payload: unknown, expectedDeviceId: string) {
    const message = validMessage(payload, expectedDeviceId)
    if (!message || (message.cmd !== 'preDeploy' && message.cmd !== 'deploy') || !boundedText(message.kind)) return

    const data = objectRecord(message.data)
    const appInfo = objectRecord(data?.appInfo)
    if (!appInfo || !boundedText(appInfo.modelName)) return
    for (const field of ['softVer', 'DeviceType']) {
        if (appInfo[field] !== undefined && !boundedText(appInfo[field])) return
    }
    return message as ClipDeployMessage
}

type ClientWithExtra = Client & {
    deviceObj: undefined | Device
    deployMsg: undefined | ClipDeployMessage
}

type DeviceAcceptorEvents = {
    newDevice: (dev: Device) => void
    dropDevice: (id: string) => void
}

export class DeviceAcceptor extends TypedEmitter<DeviceAcceptorEvents> {
    clientsById = new Map<string, Client>()
    constructor(readonly broker: Broker) {
        super()

        broker.on('publish', (packet, client) => {
            log('incoming', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)

            if (!client) return

            try {
                if (packet.topic.indexOf('clip/') >= 0) {
                    traceMqtt('device->rethink', packet)
                    const payload = JSON.parse(trimNull(Buffer.from(packet.payload)).toString('utf-8'))
                    this.mqtt(packet.topic, payload, client as ClientWithExtra)
                }
            } catch (err) {
                console.warn(err, packet.payload.toString('hex'))
            }
        })

        broker.on('disconnect', this.disconnected.bind(this))
    }

    mqtt(topic: string, payload: unknown, client: ClientWithExtra) {
        // experiment: try to support devices which use other topic formats
        topic = topic.replace(/^.*\/clip/, 'clip')

        const messageDeviceId = topicDeviceId(topic, 'message')
        const message = messageDeviceId ? validMessage(payload, messageDeviceId) : undefined
        if (message) {
            if (message.cmd === 'completeProvisioning_ack') {
                this.completeProvisioning(message.did, message, client)
                return
            }

            if (message.cmd === 'req_timesync' && client.deviceObj && message.did === client.deviceObj.id) {
                this.timeSyncRequest(client)
                return
            }

            if (client.deviceObj && message.did === client.deviceObj.id) {
                if (message.cmd === 'device_packet' && typeof message.data === 'string') {
                    const buf = Buffer.from(message.data, 'hex')
                    client.deviceObj.emit('data', buf)
                }

                // Preserve the complete device JSON for the cloud bridge. Commands such as
                // modem_cmd cannot be represented by the legacy raw-buffer data event.
                client.deviceObj.emitBridgeMessage(message)
            }
        }

        const provisioningDeviceId = topicDeviceId(topic, 'provisioning')
        if (!provisioningDeviceId) return
        const provisioning = validMessage(payload, provisioningDeviceId)
        if (provisioning) {
            if (provisioning.cmd === 'undeploy') {
                if (
                    (client.deployMsg && client.deployMsg.did !== provisioning.did) ||
                    (client.deviceObj && client.deviceObj.id !== provisioning.did)
                )
                    return

                // The appliance is dropping its provisioning with us. Everything tied to it
                // has to go: completeProvisioning refuses a second registration while the
                // device object is still around, so leaving it would make the appliance's
                // next deploy a no-op and it would never come back. It also stops sending
                // state records in the meantime, so keeping the device would leave Home
                // Assistant showing an appliance that has quietly gone silent.
                log('status', provisioning.did, 'undeployed itself; dropping its registration')
                this.disconnected(client)
                client.deployMsg = undefined
                return
            }

            const deploy = validDeployMessage(provisioning, provisioningDeviceId)
            if (
                deploy &&
                (!client.deployMsg || client.deployMsg.did === deploy.did) &&
                (!client.deviceObj || client.deviceObj.id === deploy.did)
            ) {
                client.deployMsg = deploy
                // The appliance re-announces itself periodically; keep the latest, so a
                // bridge that connects later describes the appliance as it is now.
                if (client.deviceObj) client.deviceObj.deployProfile = deploy
                const packet = {
                    topic: `lime/devices/${deploy.did}`,
                    retain: false,
                    qos: 0 as const,
                    dup: false,
                    payload: JSON.stringify(generateDeployResponse(deploy)),
                }
                traceMqtt('rethink->device', packet)
                this.broker.publish(packet, null)
            }
        }
    }

    completeProvisioning(deviceId: unknown, payload: unknown, client: ClientWithExtra) {
        if (!isSafeDeviceId(deviceId)) return
        const ack = validMessage(payload, deviceId)
        if (ack?.cmd !== 'completeProvisioning_ack') return
        if (!client.deployMsg) {
            log('status', `${deviceId} acknowledged provisioning it never started; it will not be registered`)
            return
        }
        if (client.deployMsg.did !== deviceId) return

        if (client.deviceObj) {
            log('status', `${deviceId} acknowledged provisioning twice; keeping the registration it already has`)
            return
        }

        const existing = this.clientsById.get(deviceId)
        if (existing) {
            log('status', `${deviceId} connected again; dropping its previous connection`)
            existing.destroy()
        }

        this.clientsById.set(deviceId, client)

        const meta: Metadata = {
            modelId: client.deployMsg.kind,
            modelName: client.deployMsg.data?.appInfo?.modelName,
            swVersion: client.deployMsg.data?.appInfo?.softVer,
            deviceType: client.deployMsg.data?.appInfo?.DeviceType,
        }

        const dev = new Device(this.broker, `lime/devices/${deviceId}`, deviceId, meta, client.remoteAddress)
        dev.deployProfile = client.deployMsg
        client.deviceObj = dev
        this.emit('newDevice', dev)
    }

    timeSyncRequest(client: ClientWithExtra) {
        const now = new Date()
        const buf = Buffer.alloc(7)
        buf[0] = now.getUTCFullYear() % 100
        buf[1] = now.getUTCMonth()
        buf[2] = now.getUTCDate()
        buf[3] = now.getUTCHours()
        buf[4] = now.getUTCMinutes()
        buf[5] = now.getUTCSeconds()
        buf[6] = now.getUTCDay()

        client.deviceObj?.send('resp_timesync', 1, buf.toString('base64'))
    }

    disconnected(_client: Client) {
        const client = _client as ClientWithExtra
        if (client.deviceObj) {
            // A replacement connection may already have claimed this id before the old
            // socket's close event arrives. Do not let the old close delete the new index.
            if (this.clientsById.get(client.deviceObj.id) === client) this.clientsById.delete(client.deviceObj.id)
            this.emit('dropDevice', client.deviceObj.id)
            client.deviceObj.emit('close')
            client.deviceObj = undefined
        }
    }
}
