export const ERRORS = [
    'OK',
    'Door lock error (DE2)',
    'Door open error (DE1)',
    'Water supply error (IE)',
    'Water drain error (OE)',
    'Out of balance error (UE)',
    'Overfill error (FE)',
    'Water level sensor error (PE)',
    'Temperature sensor error (TE)',
    'Locked motor error (LE)',
    undefined,
    'Unknown error (dHE)',
    'Power fail error (PF)',
    'Unknown error (FF)',
    'Unknown error (DCE)',
    'Unknown error (AE)',
    'EEPROM error',
    'Unknown error (PS)',
    'Door sensor error (DE4)',
    'Vibration sensor error (VS)',
    'Unknown error (LE8)',
    'Unknown error (LE9)',
    'Unknown error (ED1)',
    'Unknown error (ED2)',
    'Unknown error (ED3)',
    'Unknown error (ED4)',
    'Unknown error (ED5)',
]

export const STATES = [
    'Off',
    'Ready',
    'Paused',
    'Delayed',
    'Measuring',
    'Pre-wash',
    'Washing',
    'Rinsing',
    'Spinning',
    'Drying',
    'End',
    'Cooling',
    'Rinse hold',
    undefined,
    'Refreshing',
    'Steam softening',
    'Demo',
    undefined,
    'Error',
    'Auto DT Open Pause',
]

export const COURSES: Record<number, string> = {
    1: 'Cotton',
    2: 'Ease Care',
    4: 'Eco 40-60',
    5: 'Duvet',
    7: 'Mix',
    8: 'Sports Wear',
    9: 'Night Wash',
    11: 'Gentle Care',
    12: 'Quick 14',
    13: 'Steam refresh',
    14: 'Rinse + Spin',
    18: 'Drum Clean',
    19: 'Wash + Dry',
    23: 'Spin + Drain',
    24: 'Drying',
    27: 'Wool',
    32: 'Delicate',
    34: 'Quick 30',
    36: 'Direct Wear',
    45: 'Allergy Care',
    44: 'Baby Steam Care',
    49: 'TurboWash 39',
    50: 'TurboWash 59',
    51: 'Baby Clothes',
    52: 'Children Clothing',
    53: 'School Uniform',
    54: 'Swimwear',
    55: 'Rainy Season Care',
    56: 'Lightly Soiled Refresh',
    57: 'Denim',
    58: 'Bedding',
    59: 'Sweat Stains',
    62: 'Single Garments',
    64: 'Overnight',
    66: 'Fast Wash + Dry',
    69: 'Turbo drying',
    70: 'Drying shirts',
    72: 'Sanitary',
    73: 'Small Load',
    74: 'Delicate Dresses',
    75: 'Wool',
    77: 'Cold Wash',
    100: 'Rinse + Spin',
    102: 'Powder Residue',
    107: 'Cuffs + Collars',
    108: 'Juice + Food Stains',
    110: 'Saving Time',
    111: 'Reducing Wrinkles',
}

export const TEMPERATURES = [
    undefined,
    10,
    20,
    30,
    40,
    50, // assumed
    60,
    95,
]

export const SPINS = [
    undefined,
    0,
    400,
    500, // assumed
    700, // assumed
    800,
    900, // assumed
    1000,
    1100,
    1200,
    1400,
    1600,
]

export const DRYING_MODES: Record<number, string> = {
    0: 'Off',
    2: 'Auto',
    3: '00:30',
    4: '01:00',
    5: '01:30',
    6: '02:00',
    7: '02:30',
    10: 'Iron',
    11: 'Delicate',
    12: 'Eco',
}

export const DOSES = ['Off', 'Low', 'Medium', 'High']
